# Generated by Django 4.1.6 on 2023-05-08 18:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="employee",
            managers=[("employee", django.db.models.manager.Manager()),],
        ),
    ]
