# Generated by Django 4.1.6 on 2023-05-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0002_alter_employee_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(name="employee", managers=[],),
    ]
